name = input("Your name: ")
id = input("Your ID: ")
dep = input("Your department ")
git = input("Your GitHUB Username: ")
goal = input("Your programming goal ")

print("---Student Introduction Card---")
print(f"Student name : {name}")
print(f"Student ID: {id}")
print(f"Student Department: {dep}")
print(f"Student GitHUB Username: {git}")
print(f"Student Goal:{goal}")
