name = input("Your name: ")
id = input("Your ID: ")
dep = input("Your department ")
git = input("Your GitHUB Username: ")
goal = input("Your programming goal ")

print("---Student Introduction Card---")
print("Student name : ",name)
print("Student ID: ",id)
print("Student Department: ",dep)
print("Student GitHUB Username ",git)
print("Student Goal ",goal)
